import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MobXProvider } from './MobXProvider';
import Wrapper from '@/components/wrapper/wrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Tech Nerds</title>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MobXProvider>
          <Wrapper>
            {children}
          </Wrapper>
        </MobXProvider>
      </body>
    </html>
  );
}
