GET /sales/products HTTP/1.1
Host: localhost:8080
#Host: gt2-ecommerce-api.apps.gt2software.dev
###


POST /management/products HTTP/1.1
Host: localhost:8080
#Host: gt2-ecommerce-api.apps.gt2software.dev
Content-Type: application/json

{
    "name": "Bluetooth speaker 1",
    "description": "Speaker",
    "category": "audio",
    "price": 150.99,
    "imageUrl": "https://www.svgrepo.com/show/420903/audio-hardware-sound.svg"
}
###


PUT /management/products HTTP/1.1
Host: localhost:8080
#Host: gt2-ecommerce-api.apps.gt2software.dev
Content-Type: application/json

{
    "productId": 4,
    "name": "Bluetooth speaker 2",
    "description": "Speaker",
    "category": "audio",
    "price": 150.99,
    "imageUrl": "https://www.svgrepo.com/show/420903/audio-hardware-sound.svg"
}
###

DELETE /management/products/3 HTTP/1.1
Host: localhost:8080
#Host: gt2-ecommerce-api.apps.gt2software.dev
